name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - name: Run tests only
        if: github.event_name != 'pull_request' && github.ref != 'refs/heads/master'
        run: npm test

      - name: Run tests with coverage
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        run: npm run cov

      - name: Upload coverage to Codecov
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}